sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: web-gzytlias
    region: cn-hangzhou

  wechat:
    appid: wxc77b02aeeb27e12b
    secret: bdfa0c1392511a99ec6f674b0d3c49d6
  shop:
    address: 河北省石家庄市桥西区中山西路108号
    ak: WYgOwSCni1MCUBw9nFPlYfbDu3OVGhb9
